---

- hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    -  name: Checking the reachability of nodes provided in the inventory
       action: ping

- hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
    - { role: test_download, tags: downloading }
