---

- hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    -  name: Checking the reachability of nodes provided in the inventory
       action: ping

- hosts: all
  gather_facts: true
  #connection: local
  any_errors_fatal: true
  become: yes
  roles:
    - { role: test_download, tags: downloading }
